import { useLocalSearchParams } from "expo-router";
import { FlatList, StyleSheet, Text, View } from "react-native";

import { AppScreen, EmptyState, PageHeader, formatMoney, palette } from "@/components/accounting-ui";
import { useAccounting } from "@/lib/accounting/accounting-context";

export default function TankDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { state, inventory } = useAccounting(); const tank = state.tanks.find((item) => item.id === id); const balance = tank ? inventory.find((item) => item.tankId === tank.id) : undefined; const product = tank ? state.products.find((item) => item.id === tank.productId) : undefined; const currency = state.profile?.currencySymbol || "ر.س";
  if (!tank) return <AppScreen><PageHeader title="الخزان" back /><EmptyState icon="error-outline" title="الخزان غير موجود" body="قد يكون السجل غير متاح في النسخة المحلية الحالية." /></AppScreen>;
  const movements = state.inventoryMovements.filter((item) => item.tankId === tank.id).sort((a, b) => b.occurredAt.localeCompare(a.occurredAt));
  return <AppScreen scroll={false}><View style={styles.page}><PageHeader title={tank.name} subtitle={product?.name || ""} back /><View style={styles.summary}><Text style={styles.quantity}>{balance?.quantity.toLocaleString("ar-SA") || 0} وحدة</Text><Text style={styles.meta}>السعة {tank.capacity.toLocaleString("ar-SA")} · قيمة {formatMoney(balance?.value || 0, currency)}</Text></View><Text style={styles.heading}>سجل حركة المخزون</Text><FlatList data={movements} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} renderItem={({ item }) => <View style={styles.row}><View><Text style={styles.rowTitle}>{item.kind === "opening" ? "رصيد افتتاحي" : item.kind === "purchase" ? "توريد وقود" : item.kind === "sale" ? "بيع وقود" : item.kind === "reversal" ? "عكس مستند" : "تسوية"}</Text><Text style={styles.rowDate}>{item.occurredAt} · {item.note || ""}</Text></View><View><Text style={[styles.change, item.quantityIn ? styles.in : styles.out]}>{item.quantityIn ? `+${item.quantityIn.toLocaleString("ar-SA")}` : `-${item.quantityOut.toLocaleString("ar-SA")}`}</Text><Text style={styles.rowDate}>{formatMoney(item.unitCost, currency)} للوحدة</Text></View></View>} ListEmptyComponent={<EmptyState icon="history" title="لا توجد حركات" body="لن يظهر سجل حركة قبل ترحيل رصيد أو فاتورة." />} /></View></AppScreen>;
}

const styles = StyleSheet.create({ page: { flex: 1, paddingHorizontal: 18 }, summary: { backgroundColor: palette.softPetrol, borderRadius: 18, borderColor: "#C6E2E5", borderWidth: 1, padding: 16, gap: 5 }, quantity: { color: palette.ink, fontSize: 23, fontWeight: "900", textAlign: "right" }, meta: { color: palette.muted, fontSize: 12, textAlign: "right" }, heading: { color: palette.ink, fontSize: 16, fontWeight: "800", textAlign: "right", marginTop: 18, marginBottom: 8 }, list: { paddingBottom: 30, gap: 8 }, row: { backgroundColor: palette.card, borderColor: palette.border, borderWidth: 1, borderRadius: 14, padding: 13, flexDirection: "row-reverse", justifyContent: "space-between", gap: 12 }, rowTitle: { color: palette.ink, fontSize: 14, fontWeight: "800", textAlign: "right" }, rowDate: { color: palette.muted, fontSize: 11, marginTop: 3, textAlign: "right" }, change: { fontSize: 16, fontWeight: "800", textAlign: "left" }, in: { color: palette.green }, out: { color: palette.red } });
