import { MaterialIcons } from "@expo/vector-icons";
import { router } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { AppButton, AppScreen, EmptyState, PageHeader, formatMoney, palette } from "@/components/accounting-ui";
import { useAccounting } from "@/lib/accounting/accounting-context";

export default function InventoryScreen() {
  const { state, inventory } = useAccounting();
  const currency = state.profile?.currencySymbol || "ر.س";
  return <AppScreen scroll={false}><View style={styles.page}><PageHeader title="المخزون" subtitle="الأرصدة وحركات الوقود" action={{ icon: "add", label: "تسوية فعلية", onPress: () => router.push("/inventory/reconcile" as never) }} /><FlatList data={inventory} keyExtractor={(item) => item.tankId} contentContainerStyle={styles.list} ListHeaderComponent={<View style={styles.headerBlock}><View style={styles.headerTop}><View><Text style={styles.totalLabel}>القيمة الدفترية للمخزون</Text><Text style={styles.total}>{formatMoney(inventory.reduce((sum, item) => sum + item.value, 0), currency)}</Text></View><MaterialIcons name="inventory-2" color={palette.petroleum} size={34} /></View><View style={styles.actions}><AppButton title="تسوية وجرد فعلي" icon="fact-check" onPress={() => router.push("/inventory/reconcile" as never)} /><AppButton title="إثبات مخزون افتتاحي" icon="playlist-add" onPress={() => router.push("/inventory/opening")} variant="outline" /><AppButton title="إدارة الأصناف والخزانات" icon="tune" variant="outline" onPress={() => router.push("/settings/masters")} /></View></View>} renderItem={({ item }) => {
    const tank = state.tanks.find((record) => record.id === item.tankId)!;
    const product = state.products.find((record) => record.id === item.productId);
    const fill = tank.capacity ? Math.min(100, Math.max(0, (item.quantity / tank.capacity) * 100)) : 0;
    const low = item.quantity <= tank.minimumQuantity;
    return <Pressable onPress={() => router.push(`/inventory/${tank.id}`)} style={({ pressed }) => [styles.tankCard, pressed && styles.pressed]}><View style={styles.tankTop}><View><Text style={styles.tankName}>{tank.name}</Text><Text style={styles.tankProduct}>{product?.name || "صنف غير محدد"}</Text></View><View style={[styles.badge, low && styles.badgeLow]}><Text style={[styles.badgeText, low && styles.badgeTextLow]}>{low ? "منخفض" : "سليم"}</Text></View></View><View style={styles.progressTrack}><View style={[styles.progressFill, { width: `${fill}%`, backgroundColor: low ? palette.red : palette.green }]} /></View><View style={styles.tankBottom}><Text style={styles.tankQty}>{item.quantity.toLocaleString("ar-SA")} وحدة</Text><Text style={styles.tankMeta}>من {tank.capacity.toLocaleString("ar-SA")} · متوسط {formatMoney(item.averageUnitCost, currency)}</Text></View></Pressable>;
  }} ListEmptyComponent={<EmptyState icon="inventory" title="لم تُعرّف خزانات بعد" body="أضف صنف وقود وخزاناً أولاً، ثم أثبت الرصيد الافتتاحي." action={{ title: "إدارة البيانات الأساسية", onPress: () => router.push("/settings/masters") }} />} /></View></AppScreen>;
}

const styles = StyleSheet.create({
  page: { flex: 1, paddingHorizontal: 18 }, list: { paddingBottom: 30, gap: 10 }, headerBlock: { backgroundColor: palette.softPetrol, borderColor: "#C6E2E5", borderWidth: 1, borderRadius: 18, padding: 16, gap: 14, marginBottom: 6 }, headerTop: { flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between" }, totalLabel: { color: palette.petroleum, textAlign: "right", fontSize: 13, fontWeight: "700" }, total: { color: palette.ink, textAlign: "right", fontSize: 25, fontWeight: "900", marginTop: 4 }, actions: { gap: 9 }, tankCard: { backgroundColor: palette.card, borderColor: palette.border, borderWidth: 1, borderRadius: 16, padding: 14, gap: 12 }, pressed: { opacity: 0.72 }, tankTop: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, tankName: { color: palette.ink, fontSize: 16, fontWeight: "800", textAlign: "right" }, tankProduct: { color: palette.muted, fontSize: 12, textAlign: "right", marginTop: 3 }, badge: { backgroundColor: palette.softGreen, paddingHorizontal: 9, paddingVertical: 4, borderRadius: 10 }, badgeLow: { backgroundColor: palette.softRed }, badgeText: { color: palette.green, fontSize: 11, fontWeight: "800" }, badgeTextLow: { color: palette.red }, progressTrack: { backgroundColor: "#E5ECEC", height: 9, borderRadius: 9, overflow: "hidden" }, progressFill: { height: "100%", borderRadius: 9 }, tankBottom: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "baseline" }, tankQty: { color: palette.ink, fontSize: 15, fontWeight: "800" }, tankMeta: { color: palette.muted, fontSize: 11 },
});
