import { router } from "expo-router";
import { FlatList, StyleSheet, Text, View } from "react-native";

import { AppButton, AppScreen, Card, EmptyState, PageHeader, SectionTitle, formatMoney, palette, today } from "@/components/accounting-ui";
import { useAccounting } from "@/lib/accounting/accounting-context";
import type { SaleDocument } from "@/lib/accounting/types";

export default function PumpsScreen() {
  const { state } = useAccounting();
  const currency = state.profile?.currencySymbol || "ر.س";
  const date = today();
  const readingsToday = state.pumpReadings.filter((item) => item.issueDate === date);
  const volumeToday = readingsToday.reduce((sum, item) => sum + item.quantity, 0);
  const salesFromPumps = state.documents.filter((item): item is SaleDocument => item.kind === "sale" && item.status === "posted" && item.issueDate === date && Boolean(item.pumpId)).reduce((sum, item) => sum + item.total, 0);
  return <AppScreen><PageHeader title="المضخات" subtitle="قراءات عدادات مرتبطة بفواتير البيع دون ورديات" back action={{ icon: "add", label: "إضافة مضخة", onPress: () => router.push("/settings/masters" as never) }} />
    <View style={styles.summary}><View><Text style={styles.summaryValue}>{volumeToday.toLocaleString("ar-SA")}</Text><Text style={styles.summaryLabel}>كمية مباعة عبر العدادات اليوم</Text></View><View style={styles.summaryLine} /><View><Text style={styles.summaryValue}>{formatMoney(salesFromPumps, currency)}</Text><Text style={styles.summaryLabel}>قيمة الفواتير المرتبطة اليوم</Text></View></View>
    <SectionTitle title="المضخات النشطة" action={{ label: "إضافة مضخة", onPress: () => router.push("/settings/masters" as never) }} />
    {state.pumps.length ? <View style={styles.stack}>{state.pumps.filter((item) => item.isActive).map((pump) => { const tank = state.tanks.find((item) => item.id === pump.tankId); const product = state.products.find((item) => item.id === tank?.productId); const totalQuantity = state.pumpReadings.filter((item) => item.pumpId === pump.id).reduce((sum, item) => sum + item.quantity, 0); return <Card key={pump.id}><View style={styles.pumpRow}><View><Text style={styles.pumpCode}>{pump.code}</Text><Text style={styles.pumpName}>{pump.name}</Text><Text style={styles.pumpMeta}>{tank?.name || "خزان غير محدد"} · {product?.name || ""}</Text></View><View style={styles.meter}><Text style={styles.meterLabel}>آخر عداد</Text><Text style={styles.meterValue}>{pump.lastMeterReading.toLocaleString("ar-SA")}</Text></View></View><View style={styles.pumpFoot}><Text style={styles.totalText}>إجمالي فرق العداد: {totalQuantity.toLocaleString("ar-SA")}</Text><AppButton title="تسجيل بيع من المضخة" icon="add-shopping-cart" onPress={() => router.push("/sales/new" as never)} variant="outline" /></View></Card>; })}</View> : <EmptyState icon="local-gas-station" title="لم تُضف مضخات بعد" body="أضف مضخة واربطها بخزان. ثم اخترها داخل فاتورة البيع وأدخل قراءة العداد الحالية؛ يطابق التطبيق الفرق مع كمية البيع." action={{ title: "إضافة مضخة", onPress: () => router.push("/settings/masters" as never) }} />}
    <SectionTitle title="آخر قراءات العدادات" />
    {state.pumpReadings.slice().sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, 12).map((reading) => { const pump = state.pumps.find((item) => item.id === reading.pumpId); const sale = state.documents.find((item) => item.id === reading.documentId); return <Card key={reading.id}><View style={styles.readingRow}><View><Text style={styles.readingTitle}>{pump ? `${pump.code} — ${pump.name}` : "مضخة"}</Text><Text style={styles.readingMeta}>{reading.issueDate} · {sale?.number || "فاتورة بيع"}</Text></View><View><Text style={styles.readingQty}>+{reading.quantity.toLocaleString("ar-SA")}</Text><Text style={styles.readingMeta}>{reading.previousMeterReading.toLocaleString("ar-SA")} ← {reading.currentMeterReading.toLocaleString("ar-SA")}</Text></View></View></Card>; })}
  </AppScreen>;
}

const styles = StyleSheet.create({ summary: { backgroundColor: palette.softPetrol, borderWidth: 1, borderColor: "#C6E2E5", borderRadius: 18, padding: 16, flexDirection: "row-reverse", justifyContent: "space-around", alignItems: "stretch" }, summaryValue: { color: palette.ink, fontSize: 18, fontWeight: "900", textAlign: "center" }, summaryLabel: { color: palette.muted, fontSize: 11, textAlign: "center", marginTop: 4, maxWidth: 130 }, summaryLine: { backgroundColor: "#BFD9DC", width: 1 }, stack: { gap: 10 }, pumpRow: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center", gap: 10 }, pumpCode: { color: palette.petroleum, fontSize: 12, fontWeight: "900", textAlign: "right" }, pumpName: { color: palette.ink, fontSize: 16, fontWeight: "800", textAlign: "right", marginTop: 2 }, pumpMeta: { color: palette.muted, fontSize: 11, textAlign: "right", marginTop: 3 }, meter: { backgroundColor: palette.softGold, borderRadius: 12, paddingVertical: 7, paddingHorizontal: 10 }, meterLabel: { color: "#916000", textAlign: "center", fontSize: 10, fontWeight: "700" }, meterValue: { color: palette.ink, textAlign: "center", fontSize: 15, fontWeight: "900", marginTop: 2 }, pumpFoot: { paddingTop: 10, borderTopColor: palette.border, borderTopWidth: 1, gap: 9 }, totalText: { color: palette.muted, fontSize: 12, textAlign: "right" }, readingRow: { flexDirection: "row-reverse", justifyContent: "space-between", gap: 10 }, readingTitle: { color: palette.ink, fontSize: 14, fontWeight: "800", textAlign: "right" }, readingMeta: { color: palette.muted, fontSize: 11, textAlign: "right", marginTop: 3 }, readingQty: { color: palette.green, fontSize: 16, fontWeight: "900", textAlign: "left" } });
