import { useState } from "react";
import { Alert, StyleSheet, Text, View } from "react-native";

import { AppButton, AppScreen, Card, FormInput, PageHeader, SectionTitle, SelectField, palette } from "@/components/accounting-ui";
import { useAccounting } from "@/lib/accounting/accounting-context";
import type { AccountType, ContactType } from "@/lib/accounting/types";

export default function MastersScreen() {
  const { state, addProduct, addTank, addPump, addContact, addAccount } = useAccounting();
  const [productName, setProductName] = useState(""); const [sku, setSku] = useState(""); const [salesPrice, setSalesPrice] = useState(""); const [productMin, setProductMin] = useState("0");
  const [tankName, setTankName] = useState(""); const [tankProductId, setTankProductId] = useState(""); const [capacity, setCapacity] = useState(""); const [tankMin, setTankMin] = useState("0");
  const [pumpCode, setPumpCode] = useState(""); const [pumpName, setPumpName] = useState(""); const [pumpTankId, setPumpTankId] = useState(""); const [initialReading, setInitialReading] = useState("0");
  const [contactName, setContactName] = useState(""); const [contactPhone, setContactPhone] = useState(""); const [contactType, setContactType] = useState<ContactType>("customer"); const [contactAccountId, setContactAccountId] = useState("");
  const [accountName, setAccountName] = useState(""); const [accountCode, setAccountCode] = useState(""); const [accountType, setAccountType] = useState<AccountType>("asset");
  const handle = async (task: () => Promise<void>, clear: () => void) => { try { await task(); clear(); Alert.alert("تم الحفظ", "تمت إضافة البيانات محلياً."); } catch (error) { Alert.alert("تعذر الحفظ", error instanceof Error ? error.message : "حدث خطأ غير متوقع."); } };
  const accountOptions = state.accounts.filter((account) => account.isActive).map((account) => ({ label: `${account.code} — ${account.name}`, value: account.id, note: account.type }));

  return <AppScreen><PageHeader title="البيانات الأساسية" subtitle="الأصناف والخزانات والمضخات وجهات التعامل والحسابات" back />
    <SectionTitle title="صنف وقود جديد" />
    <Card><FormInput label="اسم الصنف" value={productName} onChangeText={setProductName} placeholder="مثال: بنزين 95" /><View style={styles.row}><View style={styles.half}><FormInput label="رمز الصنف" value={sku} onChangeText={setSku} placeholder="G95" /></View><View style={styles.half}><FormInput label="سعر البيع" value={salesPrice} onChangeText={setSalesPrice} placeholder="0.00" keyboardType="numeric" /></View></View><FormInput label="الحد الأدنى للكمية" value={productMin} onChangeText={setProductMin} placeholder="0" keyboardType="numeric" /><AppButton title="إضافة صنف" icon="add" onPress={() => handle(() => addProduct({ name: productName, sku, salesPrice: Number(salesPrice), minimumQuantity: Number(productMin) }), () => { setProductName(""); setSku(""); setSalesPrice(""); setProductMin("0"); })} /></Card>
    <SectionTitle title="خزان جديد" />
    <Card><FormInput label="اسم الخزان" value={tankName} onChangeText={setTankName} placeholder="مثال: خزان بنزين 95" /><SelectField label="صنف الخزان" value={tankProductId} placeholder="اختر الصنف" options={state.products.filter((item) => item.isActive).map((item) => ({ label: item.name, value: item.id, note: item.sku }))} onChange={setTankProductId} /><View style={styles.row}><View style={styles.half}><FormInput label="سعة الخزان" value={capacity} onChangeText={setCapacity} placeholder="0" keyboardType="numeric" /></View><View style={styles.half}><FormInput label="حد التنبيه" value={tankMin} onChangeText={setTankMin} placeholder="0" keyboardType="numeric" /></View></View><AppButton title="إضافة خزان" icon="add" onPress={() => handle(() => addTank({ name: tankName, productId: tankProductId, capacity: Number(capacity), minimumQuantity: Number(tankMin) }), () => { setTankName(""); setTankProductId(""); setCapacity(""); setTankMin("0"); })} /></Card>
    <SectionTitle title="مضخة جديدة" />
    <Card tone="petrol"><Text style={styles.pumpNote}>ترتبط كل مضخة بخزان واحد. القراءة الابتدائية هي نقطة بداية عداد المضخة فقط، ولا تنشئ حركة مخزون أو قيداً محاسبياً.</Text><View style={styles.row}><View style={styles.half}><FormInput label="رمز المضخة" value={pumpCode} onChangeText={setPumpCode} placeholder="P-01" /></View><View style={styles.half}><FormInput label="اسم المضخة" value={pumpName} onChangeText={setPumpName} placeholder="مضخة 1" /></View></View><SelectField label="خزان المضخة" value={pumpTankId} placeholder="اختر الخزان" options={state.tanks.filter((item) => item.isActive).map((item) => ({ label: item.name, value: item.id, note: state.products.find((product) => product.id === item.productId)?.name || "" }))} onChange={setPumpTankId} /><FormInput label="قراءة العداد الابتدائية" value={initialReading} onChangeText={setInitialReading} placeholder="0" keyboardType="numeric" /><AppButton title="إضافة مضخة" icon="local-gas-station" onPress={() => handle(() => addPump({ code: pumpCode, name: pumpName, tankId: pumpTankId, initialMeterReading: Number(initialReading) }), () => { setPumpCode(""); setPumpName(""); setPumpTankId(""); setInitialReading("0"); })} /></Card>
    <SectionTitle title="عميل أو مورد" />
    <Card><FormInput label="الاسم" value={contactName} onChangeText={setContactName} placeholder="اسم العميل أو المورد" /><View style={styles.row}><View style={styles.half}><SelectField label="النوع" value={contactType} placeholder="اختر النوع" options={[{ label: "عميل", value: "customer" }, { label: "مورد", value: "supplier" }]} onChange={(value) => { setContactType(value as ContactType); setContactAccountId(""); }} /></View><View style={styles.half}><FormInput label="الهاتف (اختياري)" value={contactPhone} onChangeText={setContactPhone} placeholder="05…" keyboardType="numeric" /></View></View><SelectField label="حساب الطرف (اختياري)" value={contactAccountId} placeholder={contactType === "customer" ? "الافتراضي: ذمم العملاء" : "الافتراضي: ذمم الموردين"} options={accountOptions.filter((item) => contactType === "customer" ? state.accounts.find((account) => account.id === item.value)?.type === "asset" : state.accounts.find((account) => account.id === item.value)?.type === "liability")} onChange={setContactAccountId} /><AppButton title="إضافة جهة تعامل" icon="person-add" onPress={() => handle(() => addContact({ name: contactName, type: contactType, phone: contactPhone, accountId: contactAccountId || undefined }), () => { setContactName(""); setContactPhone(""); setContactAccountId(""); })} /></Card>
    <SectionTitle title="حساب إضافي" />
    <Card tone="petrol"><FormInput label="رمز الحساب" value={accountCode} onChangeText={setAccountCode} placeholder="مثال: 1140" /><FormInput label="اسم الحساب" value={accountName} onChangeText={setAccountName} placeholder="مثال: حساب مصاريف النقل" /><SelectField label="نوع الحساب" value={accountType} placeholder="اختر النوع" options={[{ label: "أصل", value: "asset" }, { label: "التزام", value: "liability" }, { label: "حق ملكية", value: "equity" }, { label: "إيراد", value: "revenue" }, { label: "مصروف", value: "expense" }]} onChange={(value) => setAccountType(value as AccountType)} /><AppButton title="إضافة حساب" icon="account-balance" onPress={() => handle(() => addAccount({ code: accountCode, name: accountName, type: accountType }), () => { setAccountName(""); setAccountCode(""); setAccountType("asset"); })} variant="outline" /></Card>
    <SectionTitle title="الملخص" />
    <Card><Text style={styles.summary}>الأصناف: {state.products.length} · الخزانات: {state.tanks.length} · المضخات: {state.pumps.length} · الجهات: {state.contacts.length} · الحسابات: {state.accounts.length}</Text><Text style={styles.note}>لا تُزال الحسابات النظامية أو تعدّل من هذه الشاشة. تُنشأ الأرصدة والحركات من المستندات المرحّلة فقط.</Text></Card>
  </AppScreen>;
}

const styles = StyleSheet.create({ row: { flexDirection: "row-reverse", gap: 10 }, half: { flex: 1 }, pumpNote: { color: palette.ink, fontSize: 12, textAlign: "right", lineHeight: 20 }, summary: { color: palette.ink, fontSize: 14, fontWeight: "700", textAlign: "right" }, note: { color: palette.muted, fontSize: 12, lineHeight: 20, textAlign: "right" } });
