import { router } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { AppButton, AppScreen, EmptyState, PageHeader, formatMoney, palette } from "@/components/accounting-ui";
import { useAccounting } from "@/lib/accounting/accounting-context";

export default function JournalsScreen() {
  const { state } = useAccounting(); const currency = state.profile?.currencySymbol || "ر.س";
  const entries = [...state.journalEntries].sort((a, b) => b.entryDate.localeCompare(a.entryDate));
  return <AppScreen scroll={false}><View style={styles.page}><PageHeader title="القيود اليومية" subtitle="كل قيود النظام متوازنة وغير قابلة للتعديل" back action={{ icon: "add", label: "قيد يدوي", onPress: () => router.push("/accounting/journals/new" as never) }} /><FlatList data={entries} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ListHeaderComponent={<View style={styles.info}><Text style={styles.infoTitle}>قاعدة الدفتر</Text><Text style={styles.infoBody}>القيد المرحّل لا يعدّل ولا يحذف. استخدم مستند عكس في حال الخطأ، أو أضف قيداً تصحيحياً متوازناً.</Text><AppButton title="إضافة قيد يدوي" icon="edit-note" onPress={() => router.push("/accounting/journals/new" as never)} /></View>} renderItem={({ item }) => { const total = item.lines.reduce((sum, line) => sum + line.debit, 0); return <Pressable onPress={() => router.push(`/documents/${item.documentId}` as never)} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><View style={styles.rowTop}><View><Text style={styles.number}>{item.number}</Text><Text style={styles.description}>{item.description}</Text></View><Text style={styles.date}>{item.entryDate}</Text></View><View style={styles.rowBottom}><Text style={styles.amount}>{formatMoney(total, currency)}</Text><Text style={styles.balanced}>مدين = دائن</Text></View></Pressable>; }} ListEmptyComponent={<EmptyState icon="menu-book" title="لا توجد قيود بعد" body="تظهر القيود تلقائياً عند ترحيل المخزون الافتتاحي أو المبيعات أو المشتريات." />} /></View></AppScreen>;
}

const styles = StyleSheet.create({ page: { flex: 1, paddingHorizontal: 18 }, list: { gap: 9, paddingBottom: 30 }, info: { backgroundColor: palette.softPetrol, borderColor: "#C6E2E5", borderWidth: 1, borderRadius: 18, padding: 16, gap: 9, marginBottom: 5 }, infoTitle: { color: palette.petroleum, fontSize: 15, fontWeight: "800", textAlign: "right" }, infoBody: { color: palette.ink, lineHeight: 20, fontSize: 12, textAlign: "right" }, row: { backgroundColor: palette.card, borderWidth: 1, borderColor: palette.border, borderRadius: 16, padding: 14, gap: 10 }, rowTop: { flexDirection: "row-reverse", justifyContent: "space-between", gap: 10 }, number: { color: palette.petroleum, fontSize: 12, fontWeight: "800", textAlign: "right" }, description: { color: palette.ink, fontSize: 14, fontWeight: "700", textAlign: "right", marginTop: 3, maxWidth: 230 }, date: { color: palette.muted, fontSize: 11 }, rowBottom: { paddingTop: 9, borderTopColor: palette.border, borderTopWidth: 1, flexDirection: "row-reverse", justifyContent: "space-between" }, amount: { color: palette.ink, fontSize: 14, fontWeight: "800" }, balanced: { color: palette.green, fontSize: 11, fontWeight: "800" }, pressed: { opacity: 0.7 } });
